mongodb:
  host: localhost
  port: 27017
  auth:
    username: root
    password: root
tokens:
  accessToken:
    secret: access_token_secret
    expiration: 120
  refreshToken:
    secret: refresh_token_secret
    expiration: 10368000
  apiToken:
    secret: api_token_secret
    expiration: 10368000
